// <auto-generated />
using IdentityServerApp.AuthServer.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace IdentityServerApp.AuthServer.Migrations
{
    [DbContext(typeof(CustomDbContext))]
    partial class CustomDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("IdentityServerApp.AuthServer.Models.CustomUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CustomUser");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "İzmir",
                            Email = "yan@askin.com",
                            Password = "Pass123",
                            UserName = "Yan"
                        },
                        new
                        {
                            Id = 2,
                            City = "Ankara",
                            Email = "can@askin.com",
                            Password = "Pass123",
                            UserName = "Can"
                        },
                        new
                        {
                            Id = 3,
                            City = "Bursa",
                            Email = "dan@askin.com",
                            Password = "Pass123",
                            UserName = "Dan"
                        },
                        new
                        {
                            Id = 4,
                            City = "Van",
                            Email = "man@askin.com",
                            Password = "Pass123",
                            UserName = "Man"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
